### ISSUE TITLE
Failing to build on Cygwin

### ISSUE THREAD

**Issue by dmeador** [davidm/luacom#28]
Failing to compile on cygwin (v3.2.3), See errors attached.  Any ideas on how to fix this?  

.../luacom/luacom/build (master)$ cmake --build .      [  4%] Generating luacom5.loh
[  9%] Building CXX object CMakeFiles/luacom.dir/src/dll/luacom_dll.cpp.o
[ 13%] Building CXX object CMakeFiles/luacom.dir/src/library/LuaAux.cpp.o
[ 18%] Building CXX object CMakeFiles/luacom.dir/src/library/luabeans.cpp.o
[ 22%] Building CXX object CMakeFiles/luacom.dir/src/library/luacom.cpp.o
In file included from /usr/include/w32api/wtypes.h:23,
                 from /usr/include/w32api/winscard.h:10,
                 from /usr/include/w32api/windows.h:97,
                 from /usr/include/w32api/rpc.h:16,
                 from /usr/include/w32api/objbase.h:7,
                 from /usr/include/w32api/ole2.h:17,
                 from .../luacom/luacom/src/library/luacom.cpp:14:
/usr/include/w32api/wtypesbase.h:321:5: error: ‘byte’ does not name a type
  321 |     byte abData[1];
      |     ^~~~
/usr/include/w32api/wtypesbase.h:343:5: error: ‘byte’ does not name a type
  343 |     byte abData[1];
      |     ^~~~
/usr/include/w32api/wtypesbase.h:358:5: error: ‘byte’ does not name a type
  358 |     byte *pData;
      |     ^~~~
/usr/include/w32api/wtypesbase.h:373:5: error: ‘hyper’ does not name a type
  373 |     hyper *pData;
      |     ^~~~~
/usr/include/w32api/wtypesbase.h:373:5: note: the macro ‘hyper’ had not yet been defined
In file included from /usr/include/w32api/objbase.h:8,
                 from /usr/include/w32api/ole2.h:17,
                 from.../luacom/luacom/src/library/luacom.cpp:14:
/usr/include/w32api/rpcndr.h:69: note: it was later defined here
   69 | #define hyper /* __MINGW_EXTENSION */ __int64
      |
In file included from /usr/include/w32api/wtypes.h:23,
                 from /usr/include/w32api/winscard.h:10,
                 from /usr/include/w32api/windows.h:97,
                 from /usr/include/w32api/rpc.h:16,
                 from /usr/include/w32api/objbase.h:7,
                 from /usr/include/w32api/ole2.h:17,
                 from .../luacom/luacom/src/library/luacom.cpp:14:
/usr/include/w32api/wtypesbase.h:379:9: error: ‘boolean’ does not name a type; did you mean ‘bool’?
  379 | typedef boolean BOOLEAN;
      |         ^~~~~~~
      |         bool
In file included from /usr/include/w32api/winscard.h:10,
                 from /usr/include/w32api/windows.h:97,
                 from /usr/include/w32api/rpc.h:16,
                 from /usr/include/w32api/objbase.h:7,
                 from /usr/include/w32api/ole2.h:17,
                 from .../luacom/luacom/src/library/luacom.cpp:14:
/usr/include/w32api/wtypes.h:46:5: error: ‘byte’ does not name a type
   46 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:54:5: error: ‘byte’ does not name a type
   54 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:59:5: error: ‘byte’ does not name a type
   59 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:63:5: error: ‘byte’ does not name a type
   63 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:68:5: error: ‘byte’ does not name a type
   68 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:73:5: error: ‘byte’ does not name a type
   73 |     byte data[1];
      |     ^~~~
/usr/include/w32api/wtypes.h:299:5: error: ‘byte’ does not name a type
  299 |     byte pBuffer[1];
      |     ^~~~
make[2]: *** [CMakeFiles/luacom.dir/build.make:124: CMakeFiles/luacom.dir/src/library/luacom.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/luacom.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
